# Generated by Django 5.1.2 on 2024-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Unknown', max_length=200)),
                ('lastname', models.CharField(default='Unknown', max_length=200)),
                ('nation', models.CharField(default='Unknown', max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('overall', models.IntegerField(default=0)),
                ('position', models.CharField(default='Unknown', max_length=200)),
                ('speed', models.IntegerField(default=0)),
                ('shooting', models.IntegerField(default=0)),
                ('passing', models.IntegerField(default=0)),
                ('dribbling', models.IntegerField(default=0)),
                ('defending', models.IntegerField(default=0)),
                ('physical', models.IntegerField(default=0)),
                ('gkrating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('formation', models.IntegerField(default=0)),
            ],
        ),
    ]
