# Generated by Django 5.1.2 on 2024-12-18 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fullgame.teams'),
        ),
    ]
