# Generated by Django 5.1.2 on 2024-12-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullgame', '0002_players_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
